package com.asml.apa.wta.spark.listener;

import static org.assertj.core.api.Assertions.assertThat;

import com.asml.apa.wta.spark.BaseSparkJobIntegrationTest;
import org.junit.jupiter.api.Test;

class ApplicationLevelIntegrationTest extends BaseSparkJobIntegrationTest {

  @Test
  void testSparkTaskParentChildrenField() {
    sut1.registerTaskListener();
    sut1.registerStageListener();
    sut1.registerJobListener();
    sut1.registerApplicationListener();
    invokeJob();
    invokeJob();
    invokeJob();
    stopJob();

    assertThat(sut1.getTaskLevelListener().getProcessedObjects().count()).isEqualTo(6);
    assertThat(sut1.getTaskLevelListener().getProcessedObjects().head().getParents())
        .isEmpty();
    assertThat(sut1.getTaskLevelListener().getProcessedObjects().head().getChildren())
        .isNotEmpty();
    assertThat(sut1.getTaskLevelListener()
            .getProcessedObjects()
            .drop(1)
            .head()
            .getParents())
        .isNotEmpty();
    assertThat(sut1.getTaskLevelListener()
            .getProcessedObjects()
            .drop(1)
            .head()
            .getChildren())
        .isEmpty();
    assertThat(sut1.getTaskLevelListener()
            .getProcessedObjects()
            .drop(2)
            .head()
            .getParents())
        .isEmpty();
    assertThat(sut1.getTaskLevelListener()
            .getProcessedObjects()
            .drop(2)
            .head()
            .getChildren())
        .isNotEmpty();
    assertThat(sut1.getTaskLevelListener()
            .getProcessedObjects()
            .drop(3)
            .head()
            .getParents())
        .isNotEmpty();
    assertThat(sut1.getTaskLevelListener()
            .getProcessedObjects()
            .drop(3)
            .head()
            .getChildren())
        .isEmpty();
    assertThat(sut1.getTaskLevelListener()
            .getProcessedObjects()
            .drop(4)
            .head()
            .getParents())
        .isEmpty();
    assertThat(sut1.getTaskLevelListener()
            .getProcessedObjects()
            .drop(4)
            .head()
            .getChildren())
        .isNotEmpty();
    assertThat(sut1.getTaskLevelListener()
            .getProcessedObjects()
            .drop(5)
            .head()
            .getParents())
        .isNotEmpty();
    assertThat(sut1.getTaskLevelListener()
            .getProcessedObjects()
            .drop(5)
            .head()
            .getChildren())
        .isEmpty();
  }

  @Test
  void testSparkStageParentChildrenField() {
    sut2.registerStageListener();
    sut2.registerJobListener();
    sut2.registerApplicationListener();
    invokeJob();
    invokeJob();
    invokeJob();
    stopJob();
    assertThat(sut2.getStageLevelListener().getProcessedObjects().count()).isEqualTo(6);
    assertThat(sut2.getStageLevelListener().getProcessedObjects().head().getParents())
        .isEmpty();
    assertThat(sut2.getStageLevelListener().getProcessedObjects().head().getChildren())
        .isNotEmpty();
    assertThat(sut2.getStageLevelListener()
            .getProcessedObjects()
            .drop(1)
            .head()
            .getParents())
        .isNotEmpty();
    assertThat(sut2.getStageLevelListener()
            .getProcessedObjects()
            .drop(1)
            .head()
            .getChildren())
        .isEmpty();
    assertThat(sut2.getStageLevelListener()
            .getProcessedObjects()
            .drop(2)
            .head()
            .getParents())
        .isEmpty();
    assertThat(sut2.getStageLevelListener()
            .getProcessedObjects()
            .drop(2)
            .head()
            .getChildren())
        .isNotEmpty();
    assertThat(sut2.getStageLevelListener()
            .getProcessedObjects()
            .drop(3)
            .head()
            .getParents())
        .isNotEmpty();
    assertThat(sut2.getStageLevelListener()
            .getProcessedObjects()
            .drop(3)
            .head()
            .getChildren())
        .isEmpty();
    assertThat(sut2.getStageLevelListener()
            .getProcessedObjects()
            .drop(4)
            .head()
            .getParents())
        .isEmpty();
    assertThat(sut2.getStageLevelListener()
            .getProcessedObjects()
            .drop(4)
            .head()
            .getChildren())
        .isNotEmpty();
    assertThat(sut2.getStageLevelListener()
            .getProcessedObjects()
            .drop(5)
            .head()
            .getParents())
        .isNotEmpty();
    assertThat(sut2.getStageLevelListener()
            .getProcessedObjects()
            .drop(5)
            .head()
            .getChildren())
        .isEmpty();
  }
}
