FROM linux-tooling-setup-image:1.0.0

RUN wget link https://dlcdn.apache.org/spark/spark-3.2.4/spark-3.2.4-bin-hadoop3.2.tgz
RUN tar xvf spark-3.2.4-bin-hadoop3.2.tgz
#scala 2.13.5
#edit path for spark&scala
